# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-dpl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
  namespace: mariadb-dpl
  labels:
    app: mariadb-deploy
spec:
  selector:
    matchLabels:
      app: mariadb-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb-deploy
    spec:
      containers:
      - name: mariadb-deploy
        image: mariadb:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "128m"
          requests:
            memory: "128Mi"
            cpu: "64m"
        ports:
        - containerPort: 8000
          name: mariadb-deploy
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: mariadb-dpl
spec:
  selector:
    app: mariadb-service
  type: NodePort
  ports:
  - name: mariadb-service
    protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30002
---
