# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-replica
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: maria-replica
  namespace: mariadb-replica
  labels:
    app: maria-replica
spec:
  selector:
    matchLabels:
      app: maria-replica
  replicas: 3
  template:
    metadata:
      labels:
        app: maria-replica
    spec:
      containers:
      - name: maria-replica
        image: mariadb:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "128m"
          requests:
            memory: "128Mi"
            cpu: "64m"
        ports:
        - containerPort: 80
          name: maria-replica
---
